# version: '3.8'
# services:
#   api:
#     container_name: "docker-fastapi-spacy"
#     build: .
#     ports:
#       - 8080:8000
#     volumes:
#       - ./app:/usr/src/app
 
version: '3.8'

services:
  api:
    container_name: "docker-fastapi-spacy"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    working_dir: /usr/src/app
    environment:
      # https://h2oai.github.io/wave/docs/configuration#configuring-your-app
      - H2O_APP_ADDRESS=http://server:8000
      - H2O_WAVE_ADDRESS=http://server:10101
    volumes:
      - .:/usr/src/app
    depends_on:
      - server
    tty: true
  server:
    build:
      context: .
      dockerfile: ./wave/Dockerfile
      args:
        - WAVE_VERSION=0.16.0
    working_dir: /usr/wave
    command: ./waved
    ports:
      - '10101:10101'